**Kumpulkan data dari Google Drive**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

raw_path = "/content/drive/MyDrive/Tugas Big-Data/OULAD_EarlyWarning/data/raw/"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

**Membaca setiap file csv**

In [ ]:
import pandas as pd

courses = pd.read_csv(raw_path + "courses.csv")
assessments = pd.read_csv(raw_path + "assessments.csv")
vle = pd.read_csv(raw_path + "vle.csv")
studentInfo = pd.read_csv(raw_path + "studentInfo.csv")
studentRegistration = pd.read_csv(raw_path + "studentRegistration.csv")
studentAssessment = pd.read_csv(raw_path + "studentAssessment.csv")
studentVle = pd.read_csv(raw_path + "studentVle.csv")

**Cek tabel data**

In [ ]:
from IPython.display import display, Markdown

datasets = {
    "courses": courses,
    "assessments": assessments,
    "vle": vle,
    "studentInfo": studentInfo,
    "studentRegistration": studentRegistration,
    "studentAssessment": studentAssessment,
    "studentVle": studentVle
}

summary = []

for name, df in datasets.items():
    summary.append({
        "dataset": name,
        "rows": df.shape[0],
        "columns": df.shape[1]
    })

summary_df = pd.DataFrame(summary)
display(summary_df)

for name, df in datasets.items():
    display(Markdown(f"## Dataset: `{name}`"))
    display(Markdown(f"- **Ukuran**: {df.shape[0]} baris x {df.shape[1]} kolom"))
    display(Markdown(f"- **Kolom**: {', '.join(df.columns)}"))
    display(df.head())

               dataset      rows  columns
0              courses        22        3
1          assessments       206        6
2                  vle      6364        6
3          studentInfo     32593       12
4  studentRegistration     32593        5
5    studentAssessment    173912        5
6           studentVle  10655280        6

## Dataset: `courses`

- **Ukuran**: 22 baris x 3 kolom

- **Kolom**: code_module, code_presentation, module_presentation_length

  code_module code_presentation  module_presentation_length
0         AAA             2013J                         268
1         AAA             2014J                         269
2         BBB             2013J                         268
3         BBB             2014J                         262
4         BBB             2013B                         240

## Dataset: `assessments`

- **Ukuran**: 206 baris x 6 kolom

- **Kolom**: code_module, code_presentation, id_assessment, assessment_type, date, weight

  code_module code_presentation  id_assessment assessment_type   date  weight
0         AAA             2013J           1752             TMA   19.0    10.0
1         AAA             2013J           1753             TMA   54.0    20.0
2         AAA             2013J           1754             TMA  117.0    20.0
3         AAA             2013J           1755             TMA  166.0    20.0
4         AAA             2013J           1756             TMA  215.0    30.0

## Dataset: `vle`

- **Ukuran**: 6364 baris x 6 kolom

- **Kolom**: id_site, code_module, code_presentation, activity_type, week_from, week_to

   id_site code_module code_presentation activity_type  week_from  week_to
0   546943         AAA             2013J      resource        NaN      NaN
1   546712         AAA             2013J     oucontent        NaN      NaN
2   546998         AAA             2013J      resource        NaN      NaN
3   546888         AAA             2013J           url        NaN      NaN
4   547035         AAA             2013J      resource        NaN      NaN

## Dataset: `studentInfo`

- **Ukuran**: 32593 baris x 12 kolom

- **Kolom**: code_module, code_presentation, id_student, gender, region, highest_education, imd_band, age_band, num_of_prev_attempts, studied_credits, disability, final_result

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass

## Dataset: `studentRegistration`

- **Ukuran**: 32593 baris x 5 kolom

- **Kolom**: code_module, code_presentation, id_student, date_registration, date_unregistration

,code_module,code_presentation,id_student,date_registration,date_unregistration
0,AAA,2013J,11391,-159.0,NaN
1,AAA,2013J,28400,-53.0,NaN
2,AAA,2013J,30268,-92.0,12.0
3,AAA,2013J,31604,-52.0,NaN
4,AAA,2013J,32885,-176.0,NaN

## Dataset: `studentAssessment`

- **Ukuran**: 173912 baris x 5 kolom

- **Kolom**: id_assessment, id_student, date_submitted, is_banked, score

   id_assessment  id_student  date_submitted  is_banked  score
0           1752       11391              18          0   78.0
1           1752       28400              22          0   70.0
2           1752       31604              17          0   72.0
3           1752       32885              26          0   69.0
4           1752       38053              19          0   79.0

## Dataset: `studentVle`

- **Ukuran**: 10655280 baris x 6 kolom

- **Kolom**: code_module, code_presentation, id_student, id_site, date, sum_click

  code_module code_presentation  id_student  id_site  date  sum_click
0         AAA             2013J       28400   546652   -10          4
1         AAA             2013J       28400   546652   -10          1
2         AAA             2013J       28400   546652   -10          1
3         AAA             2013J       28400   546614   -10         11
4         AAA             2013J       28400   546714   -10          1

**Cek Kolom**

In [ ]:
for name, df in datasets.items():
    print(f"\n{name}")
    print(df.columns.tolist())

courses
['code_module', 'code_presentation', 'module_presentation_length']

assessments
['code_module', 'code_presentation', 'id_assessment', 'assessment_type', 'date', 'weight']

vle
['id_site', 'code_module', 'code_presentation', 'activity_type', 'week_from', 'week_to']

studentInfo
['code_module', 'code_presentation', 'id_student', 'gender', 'region', 'highest_education', 'imd_band', 'age_band', 'num_of_prev_attempts', 'studied_credits', 'disability', 'final_result']

studentRegistration
['code_module', 'code_presentation', 'id_student', 'date_registration', 'date_unregistration']

studentAssessment
['id_assessment', 'id_student', 'date_submitted', 'is_banked', 'score']

studentVle
['code_module', 'code_presentation', 'id_student', 'id_site', 'date', 'sum_click']

**Cek Missing Values**

In [ ]:
for name, df in datasets.items():
    print(f"\nMissing values - {name}")
    print(df.isnull().sum())

Missing values - courses
code_module                   0
code_presentation             0
module_presentation_length    0
dtype: int64

Missing values - assessments
code_module           0
code_presentation     0
id_assessment         0
assessment_type       0
date                 11
weight                0
dtype: int64

Missing values - vle
id_site                 0
code_module             0
code_presentation       0
activity_type           0
week_from            5243
week_to              5243
dtype: int64

Missing values - studentInfo
code_module                0
code_presentation          0
id_student                 0
gender                     0
region                     0
highest_education          0
imd_band                1111
age_band                   0
num_of_prev_attempts       0
studied_credits            0
disability                 0
final_result               0
dtype: int64

Missing values - studentRegistration
code_module                0
code_presentation          0
id_student                 0
date_registration         45
date_unregistration    22521
dtype: int64

Missing values - studentAssessment
id_assessment       0
id_student          0
date_submitted      0
is_banked           0
score             173
dtype: int64

Missing values - studentVle
code_module          0
code_presentation    0
id_student           0
id_site              0
date                 0
sum_click            0
dtype: int64

**Ringkasan Missing Values**

In [ ]:
missing_tables = []

for dataset_name, df in datasets.items():
    missing = df.isnull().sum()
    missing = missing[missing > 0]

    for column_name, missing_count in missing.items():
        missing_tables.append({
            "Dataset": dataset_name,
            "Kolom": column_name,
            "Jumlah Missing Values": int(missing_count)
        })

missing_df = pd.DataFrame(missing_tables)
missing_df = missing_df.sort_values(by=["Dataset", "Jumlah Missing Values"], ascending=[True, False]).reset_index(drop=True)

display(missing_df)

               Dataset                Kolom  Jumlah Missing Values
0          assessments                 date                     11
1    studentAssessment                score                    173
2          studentInfo             imd_band                   1111
3  studentRegistration  date_unregistration                  22521
4  studentRegistration    date_registration                     45
5                  vle            week_from                   5243
6                  vle              week_to                   5243

In [28]:
import os

base_path = "/content/drive/MyDrive/Tugas Big-Data/OULAD_EarlyWarning/"

for root, dirs, files in os.walk(base_path):
    level = root.replace(base_path, "").count(os.sep)
    indent = " " * 4 * level
    print(f"{indent}{os.path.basename(root)}/")
    subindent = " " * 4 * (level + 1)
    for file in files:
        print(f"{subindent}{file}")

/
data/
    raw/
        studentAssessment.csv
        studentVle.csv
        assessments.csv
        vle.csv
        studentInfo.csv
        courses.csv
        studentRegistration.csv
    processed/
        merged_processed_oulad.csv
    output/
notebooks/
    Data Acquisition.ipynb
    Data Processing.ipynb
reports/
    figure/